name: conet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+10

environment:
  sdk: ">=3.0.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  azlistview: ^2.0.0
  cached_network_image: ^3.2.3
  call_log: ^4.0.0
  another_carousel_pro: ^1.0.0
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  equatable: ^2.0.5
  firebase_auth: ^4.6.1
  # firebase_auth_web: ^5.5.1
  firebase_core: ^2.13.0
  firebase_crashlytics: 3.3.1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_dialpad: ^1.0.5
  flutter_masked_text2: ^0.9.1
  flutter_phone_direct_caller: ^2.1.1
  flutter_svg: ^2.0.6
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dio: ^5.2.0+1
  retrofit: ^4.0.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  #google_maps_flutter: ^2.2.8
  http: ^1.0.0
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  intro_slider: ^4.2.0
  loading_overlay: ^0.3.0
  # location: ^4.4.0
  lottie: ^2.3.2
  lpinyin: ^2.0.3
  multiple_images_picker: ^1.0.1
  package_info_plus: ^4.0.1
  # package_info_plus_web: ^2.0.0
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  permission_handler: ^10.2.0
  pinput: ^2.2.31
  # plugin_platform_interface: ^2.1.3
  # qrscan: ^0.3.0
  qr_code_scanner: ^1.0.1
  share_plus: ^7.0.2
  shared_preferences: ^2.1.1
  # speech_to_text_platform_interface: ^2.0.1
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.11
  firebase_messaging: ^14.6.1
  path: ^1.8.3
  flutter_screenutil: ^5.8.4
  get_it: ^7.6.0

dependency_overrides:
  http: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  freezed: ^2.3.5
  retrofit_generator: ^7.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/profile.png
    - assets/icons/
    - assets/fonts/
    - assets/json/
    - assets/json/images/
    - assets/json/report/
    - assets/json/standalone/
    - assets/json/standalone/images/
    - assets/data/
  fonts:
    - family: Dreadnoughtus
      fonts:
        - asset: assets/fonts/DreadnoughtusMedium.ttf

    # In this font-family, weights are not accurate according to file name but as per figma looks
    - family: SfproRounded
      fonts:
        - asset: assets/fonts/sfpro_rounded_thin.ttf
        - weight: 300
        - asset: assets/fonts/sfpro_rounded_light.ttf
        - weight: 400
        - asset: assets/fonts/sfpro_rounded_regular.ttf
        - weight: 500
        - asset: assets/fonts/sfpro_rounded_medium.ttf
        - weight: 600
        - asset: assets/fonts/sfpro_rounded_semibold.ttf
        - weight: 700
        - asset: assets/fonts/sfpro_rounded_bold.ttf
        - weight: 800

    - family: SfproDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.ttf
        - weight: 100
        - asset: assets/fonts/SF-Pro-Display-Thin.ttf
        - weight: 200
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
        - weight: 300
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
        - weight: 400
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
        - weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
        - weight: 600
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
        - weight: 700
        - asset: assets/fonts/SF-Pro-Display-Heavy.ttf
        - weight: 800
        - asset: assets/fonts/SF-Pro-Display-Black.ttf
        - weight: 900

    - family: SfCompactDisplay
      fonts:
        - asset: assets/fonts/SF-Compact-Display-Ultralight.ttf
        - weight: 100
        - asset: assets/fonts/SF-Compact-Display-Thin.ttf
        - weight: 200
        - asset: assets/fonts/SF-Compact-Display-Light.ttf
        - weight: 300
        - asset: assets/fonts/SF-Compact-Display-Regular.ttf
        - weight: 400
        - asset: assets/fonts/SF-Compact-Display-Medium.ttf
        - weight: 500
        - asset: assets/fonts/SF-Compact-Display-Semibold.ttf
        - weight: 600
        - asset: assets/fonts/SF-Compact-Display-Bold.ttf
        - weight: 700
        - asset: assets/fonts/SF-Compact-Display-Heavy.ttf
        - weight: 800
        - asset: assets/fonts/SF-Compact-Display-Black.ttf
        - weight: 900
