// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdtX4PRxqqR6QOoQDdo3l39T_wOvMKBRg',
    appId: '1:953426519038:web:9a67d2e286ae6cdb6bd6af',
    messagingSenderId: '953426519038',
    projectId: 'konet-ccc15',
    authDomain: 'konet-ccc15.firebaseapp.com',
    storageBucket: 'konet-ccc15.appspot.com',
    measurementId: 'G-YDV5C9424Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1ndXHYkmfnIg9VL6vFJXcTXpJ6fio0M',
    appId: '1:953426519038:android:4ec3414bfacb6d0b6bd6af',
    messagingSenderId: '953426519038',
    projectId: 'konet-ccc15',
    storageBucket: 'konet-ccc15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrDdaT19G0d7Y2xgkBveW1A6rE-DIqPr4',
    appId: '1:953426519038:ios:bdfaed96710de69c6bd6af',
    messagingSenderId: '953426519038',
    projectId: 'konet-ccc15',
    storageBucket: 'konet-ccc15.appspot.com',
    iosClientId: '953426519038-anbo49ecfnlsjvptf3loff2oqj6pvp0f.apps.googleusercontent.com',
    iosBundleId: 'com.konet.in',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrDdaT19G0d7Y2xgkBveW1A6rE-DIqPr4',
    appId: '1:953426519038:ios:4c8ad5f4a88970ad6bd6af',
    messagingSenderId: '953426519038',
    projectId: 'konet-ccc15',
    storageBucket: 'konet-ccc15.appspot.com',
    iosClientId: '953426519038-uicm3mbfg4hoporfu4ej0p1vbbihfju1.apps.googleusercontent.com',
    iosBundleId: 'com.shade6.conet.conet',
  );
}
