import 'package:conet/utils/custom_fonts.dart';
import 'package:conet/utils/theme.dart';
import 'package:flutter/material.dart';

class ConetTextTheme {
  static const TextTheme androidTextTheme = TextTheme(
    headline1: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 34,
      fontWeight: FontWeight.w700,
      fontStyle: FontStyle.normal,
    ),
    headline2: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 20,
      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
    ),
    headline3: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      color: AppColor.blackColor,
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
      fontSize: 18,
      letterSpacing: 0.2,
    ),
    headline4: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontWeight: FontWeight.w600,
      fontSize: 18,
    ),
    headline5: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 15,
      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
    ),
    headline6: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 13,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    bodyText1: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 15,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    bodyText2: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontWeight: FontWeight.w400,
      fontSize: 13,
    ),
    caption: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 10,
      fontWeight: FontWeight.w100,
      fontStyle: FontStyle.normal,
    ),
    button: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 18,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
  );

  static const TextTheme iosTextTheme = TextTheme(
    headline1: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 34,
      fontWeight: FontWeight.w700,
      fontStyle: FontStyle.normal,
    ),
    headline2: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 20,
      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
    ),
    headline3: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      color: AppColor.blackColor,
      fontWeight: FontWeight.w300,
      fontStyle: FontStyle.normal,
      fontSize: 18,
      letterSpacing: 0.2,
    ),
    headline4: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontWeight: FontWeight.w600,
      fontSize: 18,
    ),
    headline5: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 15,
      fontWeight: FontWeight.w600,
      fontStyle: FontStyle.normal,
      letterSpacing: 0.4,
    ),
    headline6: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 13,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    bodyText1: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 15,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    bodyText2: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontWeight: FontWeight.w400,
      fontSize: 13,
    ),
    caption: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 10,
      fontWeight: FontWeight.w100,
      fontStyle: FontStyle.normal,
    ),
    button: TextStyle(
      fontFamily: kSfproRoundedFontFamily,
      inherit: true,
      color: AppColor.blackColor,
      fontSize: 18,
      fontWeight: FontWeight.w500,
      fontStyle: FontStyle.normal,
    ),
  );
}
